const Currencies = (() => {
  const DEFAULT_CURRENCIES = {
    BYN: {
      name: 'Belarusian Ruble',
      symbol: 'BYN',
      identifiers: ['BYN', 'Br', 'бел. руб.', 'р. бел', 'руб.', 'р.', 'ƃ'],
      domains: ['.by', '.бел'],
    },
    RUB: {
      name: 'Russian Ruble',
      symbol: '₽',
      identifiers: ['RUB', '₽', 'руб.', 'р.'],
      domains: ['.ru', '.рф'],
    },
    USD: {
      name: 'US Dollar',
      symbol: '$',
      identifiers: ['USD', '$'],
      domains: [],
    },
    EUR: {
      name: 'Euro',
      symbol: '€',
      identifiers: ['EUR', '€'],
      domains: [],
    },
    PLN: {
      name: 'Polish Zloty',
      symbol: 'zł',
      identifiers: ['PLN', 'zł'],
      domains: ['.pl'],
    },
    UAH: {
      name: 'Ukrainian Hryvnia',
      symbol: '₴',
      identifiers: ['UAH', '₴', 'грн.'],
      domains: ['.ua'],
    },
    CZK: {
      name: 'Czech Koruna',
      symbol: 'Kč',
      identifiers: ['CZK', 'Kč'],
      domains: ['.cz'],
    },
    TRY: {
      name: 'Turkish Lira',
      symbol: '₺',
      identifiers: ['TRY', '₺', 'TL'],
      domains: ['.tr'],
    },
    CAD: {
      name: 'Canadian Dollar',
      symbol: 'CA$',
      identifiers: ['CAD', 'CA$', 'C$'],
      domains: ['.ca'],
    },
    BRL: {
      name: 'Brazilian Real',
      symbol: 'R$',
      identifiers: ['BRL', 'R$'],
      domains: ['.br'],
    },
    GBP: {
      name: 'British Pound',
      symbol: '£',
      identifiers: ['GBP', '£'],
      domains: ['.co.uk', '.uk'],
    },
    AED: {
      name: 'UAE Dirham',
      symbol: 'AED',
      identifiers: ['AED', 'Dh', 'د.إ'],
      domains: ['.ae'],
    },
    AFN: {
      name: 'Afghan Afghani',
      symbol: '؋',
      identifiers: ['AFN', '؋', 'Af'],
      domains: ['.af'],
    },
    ALL: {
      name: 'Albanian Lek',
      symbol: 'L',
      identifiers: ['ALL', 'Lek'],
      domains: ['.al'],
    },
    AMD: {
      name: 'Armenian Dram',
      symbol: '֏',
      identifiers: ['AMD', '֏', 'dram'],
      domains: ['.am'],
    },
    ANG: {
      name: 'Netherlands Antillean Guilder',
      symbol: 'ƒ',
      identifiers: ['ANG', 'ƒ', 'NAƒ'],
      domains: ['.cw', '.sx'],
    },
    AOA: {
      name: 'Angolan Kwanza',
      symbol: 'Kz',
      identifiers: ['AOA', 'Kz'],
      domains: ['.ao'],
    },
    ARS: {
      name: 'Argentine Peso',
      symbol: 'AR$',
      identifiers: ['ARS', 'AR$'],
      domains: ['.ar'],
    },
    AUD: {
      name: 'Australian Dollar',
      symbol: 'A$',
      identifiers: ['AUD', 'A$', 'AU$'],
      domains: [],
    },
    AWG: {
      name: 'Aruban Florin',
      symbol: 'ƒ',
      identifiers: ['AWG', 'Afl'],
      domains: ['.aw'],
    },
    AZN: {
      name: 'Azerbaijani Manat',
      symbol: '₼',
      identifiers: ['AZN', '₼', 'man.'],
      domains: ['.az'],
    },
    BAM: {
      name: 'Bosnia-Herzegovina Convertible Mark',
      symbol: 'KM',
      identifiers: ['BAM', 'KM', 'КМ'],
      domains: ['.ba'],
    },
    BBD: {
      name: 'Barbados Dollar',
      symbol: 'Bds$',
      identifiers: ['BBD', 'Bds$'],
      domains: ['.bb'],
    },
    BDT: {
      name: 'Bangladeshi Taka',
      symbol: '৳',
      identifiers: ['BDT', '৳', 'Tk'],
      domains: ['.bd'],
    },
    BGN: {
      name: 'Bulgarian Lev',
      symbol: 'лв',
      identifiers: ['BGN', 'лв', 'Lv'],
      domains: ['.bg'],
    },
    BHD: {
      name: 'Bahraini Dinar',
      symbol: 'BHD',
      identifiers: ['BHD', 'BD', 'د.ب'],
      domains: ['.bh'],
    },
    BIF: {
      name: 'Burundian Franc',
      symbol: 'FBu',
      identifiers: ['BIF', 'FBu'],
      domains: ['.bi'],
    },
    BMD: {
      name: 'Bermudian Dollar',
      symbol: 'BD$',
      identifiers: ['BMD', 'BD$'],
      domains: ['.bm'],
    },
    BND: {
      name: 'Brunei Dollar',
      symbol: 'B$',
      identifiers: ['BND', 'B$'],
      domains: ['.bn'],
    },
    BOB: {
      name: 'Bolivian Boliviano',
      symbol: 'Bs',
      identifiers: ['BOB', 'Bs'],
      domains: ['.bo'],
    },
    BSD: {
      name: 'Bahamian Dollar',
      symbol: 'B$',
      identifiers: ['BSD', 'B$'],
      domains: ['.bs'],
    },
    BTN: {
      name: 'Bhutanese Ngultrum',
      symbol: 'Nu',
      identifiers: ['BTN', 'Nu'],
      domains: ['.bt'],
    },
    BWP: {
      name: 'Botswana Pula',
      symbol: 'P',
      identifiers: ['BWP', 'P'],
      domains: ['.bw'],
    },
    BZD: {
      name: 'Belize Dollar',
      symbol: 'BZ$',
      identifiers: ['BZD', 'BZ$'],
      domains: ['.bz'],
    },
    CDF: {
      name: 'Congolese Franc',
      symbol: 'CDF',
      identifiers: ['CDF', 'FC'],
      domains: ['.cd'],
    },
    CHF: {
      name: 'Swiss Franc',
      symbol: 'CHF',
      identifiers: ['CHF', 'SFr'],
      domains: ['.ch'],
    },
    CLP: {
      name: 'Chilean Peso',
      symbol: 'CLP$',
      identifiers: ['CLP', 'CLP$'],
      domains: ['.cl'],
    },
    CNY: {
      name: 'Chinese Yuan Renminbi',
      symbol: '¥',
      identifiers: ['CNY', '¥', 'RMB', '元'],
      domains: ['.cn'],
    },
    COP: {
      name: 'Colombian Peso',
      symbol: 'COL$',
      identifiers: ['COP', 'COL$'],
      domains: ['.co'],
    },
    CRC: {
      name: 'Costa Rican Colon',
      symbol: '₡',
      identifiers: ['CRC', '₡'],
      domains: ['.cr'],
    },
    CUP: {
      name: 'Cuban Peso',
      symbol: '$MN',
      identifiers: ['CUP', '$MN'],
      domains: ['.cu'],
    },
    CVE: {
      name: 'Cabo Verde Escudo',
      symbol: 'CVE',
      identifiers: ['CVE', 'Esc'],
      domains: ['.cv'],
    },
    DJF: {
      name: 'Djiboutian Franc',
      symbol: 'Fdj',
      identifiers: ['DJF', 'Fdj'],
      domains: ['.dj'],
    },
    DKK: {
      name: 'Danish Krone',
      symbol: 'kr',
      identifiers: ['DKK', 'kr'],
      domains: ['.dk'],
    },
    DOP: {
      name: 'Dominican Peso',
      symbol: 'RD$',
      identifiers: ['DOP', 'RD$'],
      domains: ['.do'],
    },
    DZD: {
      name: 'Algerian Dinar',
      symbol: 'DA',
      identifiers: ['DZD', 'DA', 'د.ج'],
      domains: ['.dz'],
    },
    EGP: {
      name: 'Egyptian Pound',
      symbol: 'E£',
      identifiers: ['EGP', 'E£', 'LE', 'ج.م'],
      domains: ['.eg'],
    },
    ERN: {
      name: 'Eritrean Nakfa',
      symbol: 'ERN',
      identifiers: ['ERN', 'Nfk'],
      domains: ['.er'],
    },
    ETB: {
      name: 'Ethiopian Birr',
      symbol: 'Br',
      identifiers: ['ETB', 'Birr'],
      domains: ['.et'],
    },
    FJD: {
      name: 'Fiji Dollar',
      symbol: 'FJ$',
      identifiers: ['FJD', 'FJ$'],
      domains: ['.fj'],
    },
    FKP: {
      name: 'Falkland Islands Pound',
      symbol: 'FK£',
      identifiers: ['FKP', 'FK£'],
      domains: ['.fk'],
    },
    GEL: {
      name: 'Georgian Lari',
      symbol: '₾',
      identifiers: ['GEL', '₾'],
      domains: ['.ge'],
    },
    GHS: {
      name: 'Ghanaian Cedi',
      symbol: '₵',
      identifiers: ['GHS', '₵', 'GH₵'],
      domains: ['.gh'],
    },
    GIP: {
      name: 'Gibraltar Pound',
      symbol: 'GIP£',
      identifiers: ['GIP', 'GIP£'],
      domains: ['.gi'],
    },
    GMD: {
      name: 'Gambian Dalasi',
      symbol: 'GMD',
      identifiers: ['GMD', 'D'],
      domains: ['.gm'],
    },
    GNF: {
      name: 'Guinean Franc',
      symbol: 'GNF',
      identifiers: ['GNF', 'FG'],
      domains: ['.gn'],
    },
    GTQ: {
      name: 'Guatemalan Quetzal',
      symbol: 'Q',
      identifiers: ['GTQ', 'Q'],
      domains: ['.gt'],
    },
    GYD: {
      name: 'Guyanese Dollar',
      symbol: 'G$',
      identifiers: ['GYD', 'G$'],
      domains: ['.gy'],
    },
    HKD: {
      name: 'Hong Kong Dollar',
      symbol: 'HK$',
      identifiers: ['HKD', 'HK$'],
      domains: ['.hk'],
    },
    HNL: {
      name: 'Honduran Lempira',
      symbol: 'L',
      identifiers: ['HNL', 'L'],
      domains: ['.hn'],
    },
    HTG: {
      name: 'Haitian Gourde',
      symbol: 'G',
      identifiers: ['HTG', 'G'],
      domains: ['.ht'],
    },
    HUF: {
      name: 'Hungarian Forint',
      symbol: 'Ft',
      identifiers: ['HUF', 'Ft'],
      domains: ['.hu'],
    },
    IDR: {
      name: 'Indonesian Rupiah',
      symbol: 'Rp',
      identifiers: ['IDR', 'Rp'],
      domains: ['.id'],
    },
    ILS: {
      name: 'Israeli New Shekel',
      symbol: '₪',
      identifiers: ['ILS', '₪', 'NIS', 'ש"ח'],
      domains: ['.il'],
    },
    INR: {
      name: 'Indian Rupee',
      symbol: '₹',
      identifiers: ['INR', '₹', 'Rs'],
      domains: ['.in'],
    },
    IQD: {
      name: 'Iraqi Dinar',
      symbol: 'IQD',
      identifiers: ['IQD', 'د.ع'],
      domains: ['.iq'],
    },
    IRR: {
      name: 'Iranian Rial',
      symbol: '﷼',
      identifiers: ['IRR', '﷼'],
      domains: ['.ir'],
    },
    ISK: {
      name: 'Icelandic Krona',
      symbol: 'kr',
      identifiers: ['ISK', 'Íkr'],
      domains: ['.is'],
    },
    JMD: {
      name: 'Jamaican Dollar',
      symbol: 'J$',
      identifiers: ['JMD', 'J$'],
      domains: ['.jm'],
    },
    JOD: {
      name: 'Jordanian Dinar',
      symbol: 'JD',
      identifiers: ['JOD', 'JD', 'د.أ'],
      domains: ['.jo'],
    },
    JPY: {
      name: 'Japanese Yen',
      symbol: '¥',
      identifiers: ['JPY', '¥', '円'],
      domains: ['.jp'],
    },
    KES: {
      name: 'Kenyan Shilling',
      symbol: 'KSh',
      identifiers: ['KES', 'KSh'],
      domains: ['.ke'],
    },
    KGS: {
      name: 'Kyrgyzstani Som',
      symbol: 'сом',
      identifiers: ['KGS', 'сом'],
      domains: ['.kg'],
    },
    KHR: {
      name: 'Cambodian Riel',
      symbol: '៛',
      identifiers: ['KHR', '៛'],
      domains: ['.kh'],
    },
    KMF: {
      name: 'Comorian Franc',
      symbol: 'CF',
      identifiers: ['KMF', 'CF'],
      domains: ['.km'],
    },
    KPW: {
      name: 'North Korean Won',
      symbol: '₩',
      identifiers: ['KPW', '₩'],
      domains: ['.kp'],
    },
    KRW: {
      name: 'South Korean Won',
      symbol: '₩',
      identifiers: ['KRW', '₩', '원'],
      domains: ['.kr'],
    },
    KWD: {
      name: 'Kuwaiti Dinar',
      symbol: 'KD',
      identifiers: ['KWD', 'KD', 'د.ك'],
      domains: ['.kw'],
    },
    KYD: {
      name: 'Cayman Islands Dollar',
      symbol: 'CI$',
      identifiers: ['KYD', 'CI$'],
      domains: ['.ky'],
    },
    KZT: {
      name: 'Kazakhstani Tenge',
      symbol: '₸',
      identifiers: ['KZT', '₸'],
      domains: ['.kz'],
    },
    LAK: {
      name: 'Lao Kip',
      symbol: '₭',
      identifiers: ['LAK', '₭'],
      domains: ['.la'],
    },
    LBP: {
      name: 'Lebanese Pound',
      symbol: 'LL',
      identifiers: ['LBP', 'LL', 'ل.ل'],
      domains: ['.lb'],
    },
    LKR: {
      name: 'Sri Lankan Rupee',
      symbol: 'Rs',
      identifiers: ['LKR', 'SL Rs'],
      domains: ['.lk'],
    },
    LRD: {
      name: 'Liberian Dollar',
      symbol: 'L$',
      identifiers: ['LRD', 'L$'],
      domains: ['.lr'],
    },
    LSL: {
      name: 'Lesotho Loti',
      symbol: 'M',
      identifiers: ['LSL', 'M'],
      domains: ['.ls'],
    },
    LYD: {
      name: 'Libyan Dinar',
      symbol: 'LD',
      identifiers: ['LYD', 'LD', 'ل.د'],
      domains: ['.ly'],
    },
    MAD: {
      name: 'Moroccan Dirham',
      symbol: 'MAD',
      identifiers: ['MAD', 'DH', 'د.م.'],
      domains: ['.ma'],
    },
    MDL: {
      name: 'Moldovan Leu',
      symbol: 'MDL',
      identifiers: ['MDL', 'lei'],
      domains: ['.md'],
    },
    MGA: {
      name: 'Malagasy Ariary',
      symbol: 'Ar',
      identifiers: ['MGA', 'Ar'],
      domains: ['.mg'],
    },
    MKD: {
      name: 'Macedonian Denar',
      symbol: 'MKD',
      identifiers: ['MKD', 'ден'],
      domains: ['.mk'],
    },
    MMK: {
      name: 'Myanmar Kyat',
      symbol: 'K',
      identifiers: ['MMK', 'K'],
      domains: ['.mm'],
    },
    MNT: {
      name: 'Mongolian Tugrik',
      symbol: '₮',
      identifiers: ['MNT', '₮'],
      domains: ['.mn'],
    },
    MOP: {
      name: 'Macanese Pataca',
      symbol: 'MOP$',
      identifiers: ['MOP', 'MOP$'],
      domains: ['.mo'],
    },
    MRU: {
      name: 'Mauritanian Ouguiya',
      symbol: 'UM',
      identifiers: ['MRU', 'UM'],
      domains: ['.mr'],
    },
    MUR: {
      name: 'Mauritian Rupee',
      symbol: 'Rs',
      identifiers: ['MUR', 'MRs'],
      domains: ['.mu'],
    },
    MVR: {
      name: 'Maldivian Rufiyaa',
      symbol: 'Rf',
      identifiers: ['MVR', 'Rf'],
      domains: ['.mv'],
    },
    MWK: {
      name: 'Malawian Kwacha',
      symbol: 'MK',
      identifiers: ['MWK', 'MK'],
      domains: ['.mw'],
    },
    MXN: {
      name: 'Mexican Peso',
      symbol: 'Mex$',
      identifiers: ['MXN', 'Mex$'],
      domains: ['.mx'],
    },
    MYR: {
      name: 'Malaysian Ringgit',
      symbol: 'RM',
      identifiers: ['MYR', 'RM'],
      domains: ['.my'],
    },
    MZN: {
      name: 'Mozambican Metical',
      symbol: 'MTn',
      identifiers: ['MZN', 'MTn'],
      domains: ['.mz'],
    },
    NAD: {
      name: 'Namibian Dollar',
      symbol: 'N$',
      identifiers: ['NAD', 'N$'],
      domains: ['.na'],
    },
    NGN: {
      name: 'Nigerian Naira',
      symbol: '₦',
      identifiers: ['NGN', '₦'],
      domains: ['.ng'],
    },
    NIO: {
      name: 'Nicaraguan Cordoba',
      symbol: 'C$',
      identifiers: ['NIO', 'C$'],
      domains: ['.ni'],
    },
    NOK: {
      name: 'Norwegian Krone',
      symbol: 'kr',
      identifiers: ['NOK', 'kr'],
      domains: ['.no'],
    },
    NPR: {
      name: 'Nepalese Rupee',
      symbol: 'Rs',
      identifiers: ['NPR', 'NRs'],
      domains: ['.np'],
    },
    NZD: {
      name: 'New Zealand Dollar',
      symbol: 'NZ$',
      identifiers: ['NZD', 'NZ$'],
      domains: [],
    },
    OMR: {
      name: 'Omani Rial',
      symbol: 'OMR',
      identifiers: ['OMR', 'ر.ع.'],
      domains: ['.om'],
    },
    PAB: {
      name: 'Panamanian Balboa',
      symbol: 'B/.',
      identifiers: ['PAB', 'B/.'],
      domains: ['.pa'],
    },
    PEN: {
      name: 'Peruvian Sol',
      symbol: 'S/',
      identifiers: ['PEN', 'S/'],
      domains: ['.pe'],
    },
    PGK: {
      name: 'Papua New Guinean Kina',
      symbol: 'K',
      identifiers: ['PGK', 'K'],
      domains: ['.pg'],
    },
    PHP: {
      name: 'Philippine Peso',
      symbol: '₱',
      identifiers: ['PHP', '₱', 'PhP'],
      domains: ['.ph'],
    },
    PKR: {
      name: 'Pakistani Rupee',
      symbol: 'Rs',
      identifiers: ['PKR', 'PRs'],
      domains: ['.pk'],
    },
    PYG: {
      name: 'Paraguayan Guarani',
      symbol: '₲',
      identifiers: ['PYG', '₲', 'Gs'],
      domains: ['.py'],
    },
    QAR: {
      name: 'Qatari Rial',
      symbol: 'QR',
      identifiers: ['QAR', 'QR', 'ر.ق'],
      domains: ['.qa'],
    },
    RON: {
      name: 'Romanian Leu',
      symbol: 'lei',
      identifiers: ['RON', 'lei'],
      domains: ['.ro'],
    },
    RSD: {
      name: 'Serbian Dinar',
      symbol: 'RSD',
      identifiers: ['RSD', 'дин'],
      domains: ['.rs'],
    },
    RWF: {
      name: 'Rwandan Franc',
      symbol: 'FRw',
      identifiers: ['RWF', 'FRw'],
      domains: ['.rw'],
    },
    SAR: {
      name: 'Saudi Riyal',
      symbol: 'SR',
      identifiers: ['SAR', 'SR', 'ر.س'],
      domains: ['.sa'],
    },
    SBD: {
      name: 'Solomon Islands Dollar',
      symbol: 'SI$',
      identifiers: ['SBD', 'SI$'],
      domains: ['.sb'],
    },
    SCR: {
      name: 'Seychellois Rupee',
      symbol: 'SCR',
      identifiers: ['SCR', 'SR'],
      domains: ['.sc'],
    },
    SDG: {
      name: 'Sudanese Pound',
      symbol: 'SDG',
      identifiers: ['SDG', 'ج.س.'],
      domains: ['.sd'],
    },
    SEK: {
      name: 'Swedish Krona',
      symbol: 'kr',
      identifiers: ['SEK', 'kr'],
      domains: ['.se'],
    },
    SGD: {
      name: 'Singapore Dollar',
      symbol: 'S$',
      identifiers: ['SGD', 'S$'],
      domains: ['.sg'],
    },
    SHP: {
      name: 'Saint Helena Pound',
      symbol: 'SHP£',
      identifiers: ['SHP', 'SHP£'],
      domains: ['.sh'],
    },
    SLE: {
      name: 'Sierra Leonean Leone',
      symbol: 'Le',
      identifiers: ['SLE', 'Le'],
      domains: ['.sl'],
    },
    SOS: {
      name: 'Somali Shilling',
      symbol: 'SOS',
      identifiers: ['SOS', 'Sh.So.'],
      domains: ['.so'],
    },
    SRD: {
      name: 'Surinamese Dollar',
      symbol: 'SRD',
      identifiers: ['SRD'],
      domains: ['.sr'],
    },
    SSP: {
      name: 'South Sudanese Pound',
      symbol: 'SSP',
      identifiers: ['SSP'],
      domains: ['.ss'],
    },
    STN: {
      name: 'Sao Tome and Principe Dobra',
      symbol: 'Db',
      identifiers: ['STN', 'Db'],
      domains: ['.st'],
    },
    SVC: {
      name: 'Salvadoran Colon',
      symbol: 'SVC',
      identifiers: ['SVC'],
      domains: ['.sv'],
    },
    SZL: {
      name: 'Eswatini Lilangeni',
      symbol: 'SZL',
      identifiers: ['SZL', 'L'],
      domains: ['.sz'],
    },
    THB: {
      name: 'Thai Baht',
      symbol: '฿',
      identifiers: ['THB', '฿'],
      domains: ['.th'],
    },
    TJS: {
      name: 'Tajikistani Somoni',
      symbol: 'TJS',
      identifiers: ['TJS', 'Somoni'],
      domains: ['.tj'],
    },
    TMT: {
      name: 'Turkmenistani Manat',
      symbol: 'TMT',
      identifiers: ['TMT', 'm'],
      domains: ['.tm'],
    },
    TND: {
      name: 'Tunisian Dinar',
      symbol: 'DT',
      identifiers: ['TND', 'DT', 'د.ت'],
      domains: ['.tn'],
    },
    TOP: {
      name: 'Tongan Paanga',
      symbol: 'T$',
      identifiers: ['TOP', 'T$'],
      domains: ['.to'],
    },
    TTD: {
      name: 'Trinidad and Tobago Dollar',
      symbol: 'TT$',
      identifiers: ['TTD', 'TT$'],
      domains: ['.tt'],
    },
    TWD: {
      name: 'New Taiwan Dollar',
      symbol: 'NT$',
      identifiers: ['TWD', 'NT$'],
      domains: ['.tw'],
    },
    TZS: {
      name: 'Tanzanian Shilling',
      symbol: 'TSh',
      identifiers: ['TZS', 'TSh'],
      domains: ['.tz'],
    },
    UGX: {
      name: 'Ugandan Shilling',
      symbol: 'USh',
      identifiers: ['UGX', 'USh'],
      domains: ['.ug'],
    },
    UYU: {
      name: 'Uruguayan Peso',
      symbol: 'UYU$',
      identifiers: ['UYU', 'UYU$'],
      domains: ['.uy'],
    },
    UZS: {
      name: 'Uzbekistani Sum',
      symbol: 'UZS',
      identifiers: ['UZS', 'сўм'],
      domains: ['.uz'],
    },
    VES: {
      name: 'Venezuelan Bolivar Digital',
      symbol: 'Bs.D',
      identifiers: ['VES', 'Bs.D'],
      domains: ['.ve'],
    },
    VND: {
      name: 'Vietnamese Dong',
      symbol: '₫',
      identifiers: ['VND', '₫', 'đ'],
      domains: ['.vn'],
    },
    VUV: {
      name: 'Vanuatu Vatu',
      symbol: 'VT',
      identifiers: ['VUV', 'VT'],
      domains: ['.vu'],
    },
    WST: {
      name: 'Samoan Tala',
      symbol: 'WS$',
      identifiers: ['WST', 'WS$'],
      domains: ['.ws'],
    },
    XAF: {
      name: 'Central African CFA Franc',
      symbol: 'FCFA',
      identifiers: ['XAF', 'FCFA'],
      domains: [],
    },
    XCD: {
      name: 'East Caribbean Dollar',
      symbol: 'EC$',
      identifiers: ['XCD', 'EC$'],
      domains: [],
    },
    XOF: {
      name: 'West African CFA Franc',
      identifiers: ['XOF', 'CFA'],
      symbol: 'CFA',
      domains: [],
    },
    XPF: {
      name: 'CFP Franc',
      symbol: 'FCFP',
      identifiers: ['XPF', 'FCFP'],
      domains: [],
    },
    YER: {
      name: 'Yemeni Rial',
      symbol: 'YER',
      identifiers: ['YER', 'ر.ي'],
      domains: ['.ye'],
    },
    ZAR: {
      name: 'South African Rand',
      symbol: 'R',
      identifiers: ['ZAR', 'R'],
      domains: ['.za'],
    },
    ZMW: {
      name: 'Zambian Kwacha',
      symbol: 'ZK',
      identifiers: ['ZMW', 'ZK'],
      domains: ['.zm'],
    },
    ZWG: {
      name: 'Zimbabwe Gold',
      symbol: 'ZWG',
      identifiers: ['ZWG'],
      domains: ['.zw'],
    },
  };

  const POPULAR_CURRENCIES = ['USD', 'EUR', 'GBP', 'JPY', 'CNY', 'CHF', 'CAD', 'AUD', 'BYN', 'RUB', 'PLN', 'UAH', 'CZK', 'TRY', 'BRL', 'INR', 'KRW', 'SEK', 'NOK', 'DKK', 'HKD', 'SGD', 'THB', 'MXN', 'ZAR'];

  return { DEFAULT_CURRENCIES, POPULAR_CURRENCIES };
})();
